### ISSUE TITLE
[BUG] Hotbar layout configuration wrong order

### ISSUE THREAD

**Issue by Rukongai** [XIVRotationHero/xiv-rotation-hero-angular#12]
Hotbar layout configuration wrong order

Set hotbar configuration to 3x4 or 2x6

Hotbars should increment slot left to right first, then top down
These go down, then right. It looks like the 4x3 and 6x2 were rotated

I'm super super excited for this project. I've been saying that this tool should be built for years, and that desire actually got me to start learning to code.

I'm still nowhere near where I'd need to be to implement something like this, so i'll be following closely!

**Comment by SargoDarya** [comment]
Added screenshot for reference during fixing.

Additionally, the hotbar numbers are at the wrong spot.

![image](https://user-images.githubusercontent.com/404206/132119861-f73f4827-42de-4faf-9af2-6e05d7c4cd65.png)

**Comment by SargoDarya** [comment]
Hey @Rukongai ! First of all, thank you very much for the report.

As you said that you code already and it got you to start coding, I think this would be a very good first issue to get started as the change should just be a minor logical one in the hotbar.component.scss in how the width is being calculated.

Please let me know if you want to give it a try and I'll keep it for you. Otherwise I'll take this back around end of next week ;)

Cheers

**Comment by Rukongai** [comment]
i'll take a look!
